parlamentulRomaniei = {

        tipul: "Bicameral",

        cameraDeuptatilor: [{

                        presedinti: [{firstName: "Ludovic Orban", 
                                        anul: 2020, 
                                        partid: "PNL"}, 
                                     {firstName: "Marcel Ciolacu", 
                                        anul: 2016, 
                                        partid: "PSD"},
                                     {firstName: "Ludovic Orban", 
                                        anul: 2020, 
                                        partid: "PNL"}
                        ],
                         structuraPolitica: [
                                {firstName: "Buicu", 
                                       lastName: "Corneliu-Florin", 
                                       partid: "PSD", 
                                       judet:"MURES"}, 
                                {firstName: "Giurgiu", 
                                       lastName: "Adrian", 
                                       partid: "USR", 
                                       judet:"MURES"},
                                {firstName: "Giurgiu", 
                                       lastName: "Adrian", 
                                       partid: "USR", 
                                       judet:"MURES"}
                        ],
                        biroulPermanent: [
                                {presedinte: "Ludovic Orban", 
                                vicepresedinte: "Cristina Purna",
                                secretari: ["Oana Morariu", "Laurentiu Loreanu", "Marius Budai"],
                                chestori: ["Alexandra Presura", "George Crian Tuta"]}
                        ],
                        grupuriParlamentare: [
                                {grup1: "PSD", numarMembri: 110, 
                                grup2: "PNL", numarMembri: 93,
                                grup3: "USR PLUS", numarMembri: 55,
                                grup4: "UDMR", numarMembri: 33,
                                grup5: "AUR", numarMembri: 21}
                        ],
                        comisiiPermanente: [
                                {comisia: "Comisia pentru politică economică, reformă și privatizare",
                                                presedinte:"", vicepresedinte:"", secretari:"", membri:""},
                                {comisia: "Comisia pentru buget, finanțe și bănci",
                                                presedinte:"", vicepresedinte:"", secretari:"", membri:""},
                                {comisia: "Comisia pentru industrii și servicii",
                                                presedinte:"", vicepresedinte:"", secretari:"", membri:""},
                                {comisia: "Comisia pentru agricultură, silvicultură, industrie alimentară și servicii specifice",
                                                presedinte:"", vicepresedinte:"", secretari:"", membri:""},
                                {comisia: "Comisia pentru drepturile omului, culte și problemele minorităților naționale",
                                                presedinte:"", vicepresedinte:"", secretari:"", membri:""},
                                {comisia: "Comisia pentru administrație publică, amenajarea teritoriului și echilibru ecologic",
                                                presedinte:"", vicepresedinte:"", secretari:"", membri:""},
                                {comisia: "Comisia pentru muncă și protecție socială",
                                               presedinte:"", vicepresedinte:"", secretari:"", membri:""},
                                {comisia: "Comisia pentru sănătate și familie",
                                               presedinte:"", vicepresedinte:"", secretari:"", membri:""},
                                {comisia: "Comisia pentru învățământ, știință, tineret și sport",
                                               presedinte:"", vicepresedinte:"", secretari:"", membri:""},
                                {comisia: "Comisia pentru cultură, arte, mijloace de informare în masă",
                                               presedinte:"", vicepresedinte:"", secretari:"", membri:""},
                                {comisia: "Comisia juridică, de disciplină și imunități",
                                                presedinte:"", vicepresedinte:"", secretari:"", membri:""},
                                {comisia: "Comisia pentru apărare, ordine publică și siguranță națională",
                                                presedinte:"", vicepresedinte:"", secretari:"", membri:""},
                                {comisia: "Comisia pentru politică externă",
                                                presedinte:"", vicepresedinte:"", secretari:"", membri:""}, 
                                {comisia: "Comisia pentru cercetarea abuzurilor, corupției și pentru petiții",
                                                presedinte:"", vicepresedinte:"", secretari:"", membri:""},
                                {comisia: "Comisia pentru regulament",
                                                presedinte:"", vicepresedinte:"", secretari:"", membri:""},
                                {comisia: "Comisia pentru tehnologia informației și comunicațiilor",
                                                presedinte:"", vicepresedinte:"", secretari:"", membri:""},
                                {comisia: "Comisia pentru egalitatea de șanse pentru femei și bărbați",
                                                presedinte:"", vicepresedinte:"", secretari:"", membri:""},
                                {comisia: "Comisia pentru comunitățile de români din afara granițelor țării",
                                                presedinte:"", vicepresedinte:"", secretari:"", membri:""},
                                {comisia: "Comisia pentru afaceri europene",
                                                presedinte:"", vicepresedinte:"", secretari:"", membri:""}
                        ],
                        grupuriPolitice: [
                                        {partid: "PSD", procent: 33.33}, 
                                        {partid: "PNL", procent: 28.18}, 
                                        {partid:"USR PLUS", procent: 16.65}, 
                                        {partid: "AUR", procent: 10.00}, 
                                        {partid: "UDMR", procent: 6.36}, 
                                        {partid: "Monoritati", procent: 5.45}
                                ],
        }],
        
        cameraSenatului: [{
                        presedinti: [{firstName: "Anca Dragu", 
                                                anul: 2020, 
                                                partid: "PNL"}, 
                                     {firstName: "Teodor Melescanu", 
                                                anul: 2016, 
                                                partid: "PSD"},
                                     {firstName: "Calin Popescu Tariceanu", 
                                                anul: 2012, 
                                                partid: "PNL"}
                                ],
                        structuraPolitica: [
                                {firstName: "Tuca", 
                                        lastName: "Cristian", 
                                        partid: "PMP", 
                                        judet:"MURES"}, 
                                {firstName: "Pop", 
                                        lastName: "Zamfir", 
                                        partid: "USR", 
                                        judet:"MURES"},
                                {firstName: "Maior", 
                                        lastName: "Sergiu", 
                                        partid: "USR", 
                                        judet:"MURES"}
                                ],
                        biroulPermanent: [
                                {presedinte: "Anca Dragu", 
                                vicepresedinte: ["Leonard Azamfirei", "Robert Cazanciuc", "Stefan-Radu Oprea"],
                                secretari: ["Ion Mocioalcă", "Eugen Pîrvulescu", "Dan Ivan", "Sorin Lavric"],
                                chestori: ["Siminca Mirea", "Sergiu Cosmin Vlad"]}
                        ],
                        grupuriParlamentare: [
                                {grup1: "PSD", numarMembri: 47, 
                                grup2: "PNL", numarMembri: 41,
                                grup3: "USR PLUS", numarMembri: 25,
                                grup4: "UDMR", numarMembri: 9,
                                grup5: "AUR", numarMembri: 14}
                        ],
                        comisiiPermanente: [
                                {comisia: "Comisia juridică, de numiri, disciplină, imunități și validări", 
                                                presedinte:"", vicepresedinte:"", secretari:"", membri:""},
                                {comisia: "Comisia pentru constituționalitate", 
                                                presedinte:"", vicepresedinte:"", secretari:"", membri:""},
                                {comisia: "Comisia pentru buget, finanțe, activitate bancară și piață de capital", 
                                                presedinte:"", vicepresedinte:"", secretari:"", membri:""},                                
                                {comisia: "Comisia pentru politică externă", 
                                                presedinte:"", vicepresedinte:"", secretari:"", membri:""},
                                {comisia: "Comisia pentru apărare, ordine publică și siguranță națională", 
                                                presedinte:"", vicepresedinte:"", secretari:"", membri:""},
                                {comisia: "Comisia pentru afaceri europene", 
                                                presedinte:"", vicepresedinte:"", secretari:"", membri:""},
                                {comisia: "Comisia economică, industrii și servicii", 
                                                presedinte:"", vicepresedinte:"", secretari:"", membri:""},
                                {comisia: "Comisia pentru agricultură, industrie alimentară si dezvoltare rurală", 
                                                presedinte:"", vicepresedinte:"", secretari:"", membri:""},
                                {comisia: "Comisia pentru ape, păduri, pescuit și fond cinegetic", 
                                                presedinte:"", vicepresedinte:"", secretari:"", membri:""},
                                {comisia: "Comisia pentru administrație publică", 
                                                presedinte:"", vicepresedinte:"", secretari:"", membri:""},
                                {comisia: "Comisia pentru muncă, familie și protecție socială", 
                                                presedinte:"", vicepresedinte:"", secretari:"", membri:""},
                                {comisia: "Comisia pentru învățământ, știință, tineret și sport", 
                                                presedinte:"", vicepresedinte:"", secretari:"", membri:""},
                                {comisia: "Comisia pentru sănătate publică", 
                                                presedinte:"", vicepresedinte:"", secretari:"", membri:""},
                                {comisia: "Comisia pentru cultură și media", 
                                                presedinte:"", vicepresedinte:"", secretari:"", membri:""},
                                {comisia: "Comisia pentru transporturi și infrastructură", 
                                                presedinte:"", vicepresedinte:"", secretari:"", membri:""},
                                {comisia: "Comisia pentru energie, infrastructură energetică și resurse minerale", 
                                                presedinte:"", vicepresedinte:"", secretari:"", membri:""},
                                {comisia: "Comisia pentru comunicații și tehnologia informației", 
                                                presedinte:"", vicepresedinte:"", secretari:"", membri:""},
                                {comisia: "Comisia pentru drepturile omului, egalitate de șanse, culte și minorități", 
                                                presedinte:"", vicepresedinte:"", secretari:"", membri:""},
                                {comisia: "Comisia pentru comunitățile de români din afara țării", 
                                                presedinte:"", vicepresedinte:"", secretari:"", membri:""},
                                {comisia: "Comisia pentru mediu", 
                                                presedinte:"", vicepresedinte:"", secretari:"", membri:""},
                                {comisia: "Comisia pentru cercetarea abuzurilor, combaterea corupției și petiții", 
                                                presedinte:"", vicepresedinte:"", secretari:"", membri:""},
                                {comisia: "Comisia pentru regulament", 
                                                presedinte:"", vicepresedinte:"", secretari:"", membri:""},
                        ],
                        grupuriPolitice: [
                                        {partid: "PSD", procent: 34.55, numarLocuri: 47}, 
                                        {partid: "PNL", procent: 30.14, numarLocuri: 41}, 
                                        {partid:"USR PLUS", procent: 18.38, numarLocuri: 25}, 
                                        {partid: "AUR", procent: 10.29, numaLocuri: 14}, 
                                        {partid: "UDMR", procent: 6.36, numarLocuri: 9}, 
                                        
                                ],
                        }],

};
